name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          sleep 30
          echo test, and deploy your project
      - name: Create a file
        run: touch /tmp/gagandeep1
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Run test cases
        run: |
          echo "Test running"
          sleep 30
      - name: List files
        run: ls -l /tmp/
